# Generated by Django 5.1.4 on 2025-02-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="origin",
            field=models.CharField(
                choices=[
                    ("african", "Africa"),
                    ("american", "America"),
                    ("european", "Europe"),
                    ("arabic", "Arab"),
                ],
                default="african",
                max_length=20,
            ),
        ),
    ]
